train:
    data_path: 'dataset/train'
    model_path: 'models/pretrained.pt'
    batch_size: 4
    epoch: 3
    lr: 1e-4
test:
    data_path: 'dataset/test_false'
    model_path: 'models/pretrained.pt'