train:
    data_path: 'dataset/train'
    model_path: 'models/pretrained.pt'
    batch_size: 8
    clf_epoch: 10
    clf_lr: 5e-3

    bind_epoch: 1
    bind_lr: 1e-3
test:
    data_path: 'dataset/test_true'
    model_path: 'models/pretrained.pt'